services:
  dev:
    build: .
    container_name: dev-environment
    ports:
      - "${SSH_PORT:-2222}:22"  # Use SSH_PORT env var with default of 2222
    environment:
      - SSH_PORT=${SSH_PORT:-2222}
      - SSH_IMPORT_ID=${SSH_IMPORT_ID:-yourusername}  # Set this to your GitHub or Launchpad username
      - SSH_IMPORT_FROM=${SSH_IMPORT_FROM:-gh}  # Default to GitHub (gh) or use Launchpad (lp)
      - ADDITIONAL_PORTS=${ADDITIONAL_PORTS:-}  # Format: "9000:9000,27017:27017"
    volumes:
      - dev-code:/home/dev/code  # Use a named volume for code
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker-in-Docker
    restart: unless-stopped

volumes:
  dev-code:
